<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <RollForward>LatestMajor</RollForward>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>SingletonExample</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../../packages/csharp/src/GofPatterns/GofPatterns.csproj" />
  </ItemGroup>

</Project>
